// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.wolfpeng.server.protocol;

public final class MessageOuterClass {
  private MessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:server.protocol.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.server.protocol.Request request = 1;</code>
     */
    com.wolfpeng.server.protocol.RequestOuterClass.Request getRequest();
    /**
     * <code>.server.protocol.Request request = 1;</code>
     */
    com.wolfpeng.server.protocol.RequestOuterClass.RequestOrBuilder getRequestOrBuilder();

    /**
     * <code>.server.protocol.Response response = 2;</code>
     */
    com.wolfpeng.server.protocol.ResponseOuterClass.Response getResponse();
    /**
     * <code>.server.protocol.Response response = 2;</code>
     */
    com.wolfpeng.server.protocol.ResponseOuterClass.ResponseOrBuilder getResponseOrBuilder();

    /**
     * <code>.server.protocol.Notify notify = 3;</code>
     */
    com.wolfpeng.server.protocol.NotifyOuterClass.Notify getNotify();
    /**
     * <code>.server.protocol.Notify notify = 3;</code>
     */
    com.wolfpeng.server.protocol.NotifyOuterClass.NotifyOrBuilder getNotifyOrBuilder();

    public com.wolfpeng.server.protocol.MessageOuterClass.Message.PackageCase getPackageCase();
  }
  /**
   * Protobuf type {@code server.protocol.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:server.protocol.Message)
      MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.wolfpeng.server.protocol.RequestOuterClass.Request.Builder subBuilder = null;
              if (packageCase_ == 1) {
                subBuilder = ((com.wolfpeng.server.protocol.RequestOuterClass.Request) package_).toBuilder();
              }
              package_ =
                  input.readMessage(com.wolfpeng.server.protocol.RequestOuterClass.Request.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.wolfpeng.server.protocol.RequestOuterClass.Request) package_);
                package_ = subBuilder.buildPartial();
              }
              packageCase_ = 1;
              break;
            }
            case 18: {
              com.wolfpeng.server.protocol.ResponseOuterClass.Response.Builder subBuilder = null;
              if (packageCase_ == 2) {
                subBuilder = ((com.wolfpeng.server.protocol.ResponseOuterClass.Response) package_).toBuilder();
              }
              package_ =
                  input.readMessage(com.wolfpeng.server.protocol.ResponseOuterClass.Response.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.wolfpeng.server.protocol.ResponseOuterClass.Response) package_);
                package_ = subBuilder.buildPartial();
              }
              packageCase_ = 2;
              break;
            }
            case 26: {
              com.wolfpeng.server.protocol.NotifyOuterClass.Notify.Builder subBuilder = null;
              if (packageCase_ == 3) {
                subBuilder = ((com.wolfpeng.server.protocol.NotifyOuterClass.Notify) package_).toBuilder();
              }
              package_ =
                  input.readMessage(com.wolfpeng.server.protocol.NotifyOuterClass.Notify.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.wolfpeng.server.protocol.NotifyOuterClass.Notify) package_);
                package_ = subBuilder.buildPartial();
              }
              packageCase_ = 3;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wolfpeng.server.protocol.MessageOuterClass.internal_static_server_protocol_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wolfpeng.server.protocol.MessageOuterClass.internal_static_server_protocol_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wolfpeng.server.protocol.MessageOuterClass.Message.class, com.wolfpeng.server.protocol.MessageOuterClass.Message.Builder.class);
    }

    private int packageCase_ = 0;
    private java.lang.Object package_;
    public enum PackageCase
        implements com.google.protobuf.Internal.EnumLite {
      REQUEST(1),
      RESPONSE(2),
      NOTIFY(3),
      PACKAGE_NOT_SET(0);
      private final int value;
      private PackageCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PackageCase valueOf(int value) {
        return forNumber(value);
      }

      public static PackageCase forNumber(int value) {
        switch (value) {
          case 1: return REQUEST;
          case 2: return RESPONSE;
          case 3: return NOTIFY;
          case 0: return PACKAGE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public PackageCase
    getPackageCase() {
      return PackageCase.forNumber(
          packageCase_);
    }

    public static final int REQUEST_FIELD_NUMBER = 1;
    /**
     * <code>.server.protocol.Request request = 1;</code>
     */
    public com.wolfpeng.server.protocol.RequestOuterClass.Request getRequest() {
      if (packageCase_ == 1) {
         return (com.wolfpeng.server.protocol.RequestOuterClass.Request) package_;
      }
      return com.wolfpeng.server.protocol.RequestOuterClass.Request.getDefaultInstance();
    }
    /**
     * <code>.server.protocol.Request request = 1;</code>
     */
    public com.wolfpeng.server.protocol.RequestOuterClass.RequestOrBuilder getRequestOrBuilder() {
      if (packageCase_ == 1) {
         return (com.wolfpeng.server.protocol.RequestOuterClass.Request) package_;
      }
      return com.wolfpeng.server.protocol.RequestOuterClass.Request.getDefaultInstance();
    }

    public static final int RESPONSE_FIELD_NUMBER = 2;
    /**
     * <code>.server.protocol.Response response = 2;</code>
     */
    public com.wolfpeng.server.protocol.ResponseOuterClass.Response getResponse() {
      if (packageCase_ == 2) {
         return (com.wolfpeng.server.protocol.ResponseOuterClass.Response) package_;
      }
      return com.wolfpeng.server.protocol.ResponseOuterClass.Response.getDefaultInstance();
    }
    /**
     * <code>.server.protocol.Response response = 2;</code>
     */
    public com.wolfpeng.server.protocol.ResponseOuterClass.ResponseOrBuilder getResponseOrBuilder() {
      if (packageCase_ == 2) {
         return (com.wolfpeng.server.protocol.ResponseOuterClass.Response) package_;
      }
      return com.wolfpeng.server.protocol.ResponseOuterClass.Response.getDefaultInstance();
    }

    public static final int NOTIFY_FIELD_NUMBER = 3;
    /**
     * <code>.server.protocol.Notify notify = 3;</code>
     */
    public com.wolfpeng.server.protocol.NotifyOuterClass.Notify getNotify() {
      if (packageCase_ == 3) {
         return (com.wolfpeng.server.protocol.NotifyOuterClass.Notify) package_;
      }
      return com.wolfpeng.server.protocol.NotifyOuterClass.Notify.getDefaultInstance();
    }
    /**
     * <code>.server.protocol.Notify notify = 3;</code>
     */
    public com.wolfpeng.server.protocol.NotifyOuterClass.NotifyOrBuilder getNotifyOrBuilder() {
      if (packageCase_ == 3) {
         return (com.wolfpeng.server.protocol.NotifyOuterClass.Notify) package_;
      }
      return com.wolfpeng.server.protocol.NotifyOuterClass.Notify.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (packageCase_ == 1) {
        output.writeMessage(1, (com.wolfpeng.server.protocol.RequestOuterClass.Request) package_);
      }
      if (packageCase_ == 2) {
        output.writeMessage(2, (com.wolfpeng.server.protocol.ResponseOuterClass.Response) package_);
      }
      if (packageCase_ == 3) {
        output.writeMessage(3, (com.wolfpeng.server.protocol.NotifyOuterClass.Notify) package_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (packageCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (com.wolfpeng.server.protocol.RequestOuterClass.Request) package_);
      }
      if (packageCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.wolfpeng.server.protocol.ResponseOuterClass.Response) package_);
      }
      if (packageCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (com.wolfpeng.server.protocol.NotifyOuterClass.Notify) package_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wolfpeng.server.protocol.MessageOuterClass.Message)) {
        return super.equals(obj);
      }
      com.wolfpeng.server.protocol.MessageOuterClass.Message other = (com.wolfpeng.server.protocol.MessageOuterClass.Message) obj;

      boolean result = true;
      result = result && getPackageCase().equals(
          other.getPackageCase());
      if (!result) return false;
      switch (packageCase_) {
        case 1:
          result = result && getRequest()
              .equals(other.getRequest());
          break;
        case 2:
          result = result && getResponse()
              .equals(other.getResponse());
          break;
        case 3:
          result = result && getNotify()
              .equals(other.getNotify());
          break;
        case 0:
        default:
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (packageCase_) {
        case 1:
          hash = (37 * hash) + REQUEST_FIELD_NUMBER;
          hash = (53 * hash) + getRequest().hashCode();
          break;
        case 2:
          hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
          hash = (53 * hash) + getResponse().hashCode();
          break;
        case 3:
          hash = (37 * hash) + NOTIFY_FIELD_NUMBER;
          hash = (53 * hash) + getNotify().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wolfpeng.server.protocol.MessageOuterClass.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wolfpeng.server.protocol.MessageOuterClass.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wolfpeng.server.protocol.MessageOuterClass.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wolfpeng.server.protocol.MessageOuterClass.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wolfpeng.server.protocol.MessageOuterClass.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wolfpeng.server.protocol.MessageOuterClass.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wolfpeng.server.protocol.MessageOuterClass.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wolfpeng.server.protocol.MessageOuterClass.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wolfpeng.server.protocol.MessageOuterClass.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wolfpeng.server.protocol.MessageOuterClass.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wolfpeng.server.protocol.MessageOuterClass.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wolfpeng.server.protocol.MessageOuterClass.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wolfpeng.server.protocol.MessageOuterClass.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code server.protocol.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:server.protocol.Message)
        com.wolfpeng.server.protocol.MessageOuterClass.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wolfpeng.server.protocol.MessageOuterClass.internal_static_server_protocol_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wolfpeng.server.protocol.MessageOuterClass.internal_static_server_protocol_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wolfpeng.server.protocol.MessageOuterClass.Message.class, com.wolfpeng.server.protocol.MessageOuterClass.Message.Builder.class);
      }

      // Construct using com.wolfpeng.server.protocol.MessageOuterClass.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        packageCase_ = 0;
        package_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wolfpeng.server.protocol.MessageOuterClass.internal_static_server_protocol_Message_descriptor;
      }

      public com.wolfpeng.server.protocol.MessageOuterClass.Message getDefaultInstanceForType() {
        return com.wolfpeng.server.protocol.MessageOuterClass.Message.getDefaultInstance();
      }

      public com.wolfpeng.server.protocol.MessageOuterClass.Message build() {
        com.wolfpeng.server.protocol.MessageOuterClass.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wolfpeng.server.protocol.MessageOuterClass.Message buildPartial() {
        com.wolfpeng.server.protocol.MessageOuterClass.Message result = new com.wolfpeng.server.protocol.MessageOuterClass.Message(this);
        if (packageCase_ == 1) {
          if (requestBuilder_ == null) {
            result.package_ = package_;
          } else {
            result.package_ = requestBuilder_.build();
          }
        }
        if (packageCase_ == 2) {
          if (responseBuilder_ == null) {
            result.package_ = package_;
          } else {
            result.package_ = responseBuilder_.build();
          }
        }
        if (packageCase_ == 3) {
          if (notifyBuilder_ == null) {
            result.package_ = package_;
          } else {
            result.package_ = notifyBuilder_.build();
          }
        }
        result.packageCase_ = packageCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wolfpeng.server.protocol.MessageOuterClass.Message) {
          return mergeFrom((com.wolfpeng.server.protocol.MessageOuterClass.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wolfpeng.server.protocol.MessageOuterClass.Message other) {
        if (other == com.wolfpeng.server.protocol.MessageOuterClass.Message.getDefaultInstance()) return this;
        switch (other.getPackageCase()) {
          case REQUEST: {
            mergeRequest(other.getRequest());
            break;
          }
          case RESPONSE: {
            mergeResponse(other.getResponse());
            break;
          }
          case NOTIFY: {
            mergeNotify(other.getNotify());
            break;
          }
          case PACKAGE_NOT_SET: {
            break;
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wolfpeng.server.protocol.MessageOuterClass.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wolfpeng.server.protocol.MessageOuterClass.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int packageCase_ = 0;
      private java.lang.Object package_;
      public PackageCase
          getPackageCase() {
        return PackageCase.forNumber(
            packageCase_);
      }

      public Builder clearPackage() {
        packageCase_ = 0;
        package_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          com.wolfpeng.server.protocol.RequestOuterClass.Request, com.wolfpeng.server.protocol.RequestOuterClass.Request.Builder, com.wolfpeng.server.protocol.RequestOuterClass.RequestOrBuilder> requestBuilder_;
      /**
       * <code>.server.protocol.Request request = 1;</code>
       */
      public com.wolfpeng.server.protocol.RequestOuterClass.Request getRequest() {
        if (requestBuilder_ == null) {
          if (packageCase_ == 1) {
            return (com.wolfpeng.server.protocol.RequestOuterClass.Request) package_;
          }
          return com.wolfpeng.server.protocol.RequestOuterClass.Request.getDefaultInstance();
        } else {
          if (packageCase_ == 1) {
            return requestBuilder_.getMessage();
          }
          return com.wolfpeng.server.protocol.RequestOuterClass.Request.getDefaultInstance();
        }
      }
      /**
       * <code>.server.protocol.Request request = 1;</code>
       */
      public Builder setRequest(com.wolfpeng.server.protocol.RequestOuterClass.Request value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          package_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }
        packageCase_ = 1;
        return this;
      }
      /**
       * <code>.server.protocol.Request request = 1;</code>
       */
      public Builder setRequest(
          com.wolfpeng.server.protocol.RequestOuterClass.Request.Builder builderForValue) {
        if (requestBuilder_ == null) {
          package_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }
        packageCase_ = 1;
        return this;
      }
      /**
       * <code>.server.protocol.Request request = 1;</code>
       */
      public Builder mergeRequest(com.wolfpeng.server.protocol.RequestOuterClass.Request value) {
        if (requestBuilder_ == null) {
          if (packageCase_ == 1 &&
              package_ != com.wolfpeng.server.protocol.RequestOuterClass.Request.getDefaultInstance()) {
            package_ = com.wolfpeng.server.protocol.RequestOuterClass.Request.newBuilder((com.wolfpeng.server.protocol.RequestOuterClass.Request) package_)
                .mergeFrom(value).buildPartial();
          } else {
            package_ = value;
          }
          onChanged();
        } else {
          if (packageCase_ == 1) {
            requestBuilder_.mergeFrom(value);
          }
          requestBuilder_.setMessage(value);
        }
        packageCase_ = 1;
        return this;
      }
      /**
       * <code>.server.protocol.Request request = 1;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          if (packageCase_ == 1) {
            packageCase_ = 0;
            package_ = null;
            onChanged();
          }
        } else {
          if (packageCase_ == 1) {
            packageCase_ = 0;
            package_ = null;
          }
          requestBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.server.protocol.Request request = 1;</code>
       */
      public com.wolfpeng.server.protocol.RequestOuterClass.Request.Builder getRequestBuilder() {
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>.server.protocol.Request request = 1;</code>
       */
      public com.wolfpeng.server.protocol.RequestOuterClass.RequestOrBuilder getRequestOrBuilder() {
        if ((packageCase_ == 1) && (requestBuilder_ != null)) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          if (packageCase_ == 1) {
            return (com.wolfpeng.server.protocol.RequestOuterClass.Request) package_;
          }
          return com.wolfpeng.server.protocol.RequestOuterClass.Request.getDefaultInstance();
        }
      }
      /**
       * <code>.server.protocol.Request request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.wolfpeng.server.protocol.RequestOuterClass.Request, com.wolfpeng.server.protocol.RequestOuterClass.Request.Builder, com.wolfpeng.server.protocol.RequestOuterClass.RequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          if (!(packageCase_ == 1)) {
            package_ = com.wolfpeng.server.protocol.RequestOuterClass.Request.getDefaultInstance();
          }
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.wolfpeng.server.protocol.RequestOuterClass.Request, com.wolfpeng.server.protocol.RequestOuterClass.Request.Builder, com.wolfpeng.server.protocol.RequestOuterClass.RequestOrBuilder>(
                  (com.wolfpeng.server.protocol.RequestOuterClass.Request) package_,
                  getParentForChildren(),
                  isClean());
          package_ = null;
        }
        packageCase_ = 1;
        onChanged();;
        return requestBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.wolfpeng.server.protocol.ResponseOuterClass.Response, com.wolfpeng.server.protocol.ResponseOuterClass.Response.Builder, com.wolfpeng.server.protocol.ResponseOuterClass.ResponseOrBuilder> responseBuilder_;
      /**
       * <code>.server.protocol.Response response = 2;</code>
       */
      public com.wolfpeng.server.protocol.ResponseOuterClass.Response getResponse() {
        if (responseBuilder_ == null) {
          if (packageCase_ == 2) {
            return (com.wolfpeng.server.protocol.ResponseOuterClass.Response) package_;
          }
          return com.wolfpeng.server.protocol.ResponseOuterClass.Response.getDefaultInstance();
        } else {
          if (packageCase_ == 2) {
            return responseBuilder_.getMessage();
          }
          return com.wolfpeng.server.protocol.ResponseOuterClass.Response.getDefaultInstance();
        }
      }
      /**
       * <code>.server.protocol.Response response = 2;</code>
       */
      public Builder setResponse(com.wolfpeng.server.protocol.ResponseOuterClass.Response value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          package_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }
        packageCase_ = 2;
        return this;
      }
      /**
       * <code>.server.protocol.Response response = 2;</code>
       */
      public Builder setResponse(
          com.wolfpeng.server.protocol.ResponseOuterClass.Response.Builder builderForValue) {
        if (responseBuilder_ == null) {
          package_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }
        packageCase_ = 2;
        return this;
      }
      /**
       * <code>.server.protocol.Response response = 2;</code>
       */
      public Builder mergeResponse(com.wolfpeng.server.protocol.ResponseOuterClass.Response value) {
        if (responseBuilder_ == null) {
          if (packageCase_ == 2 &&
              package_ != com.wolfpeng.server.protocol.ResponseOuterClass.Response.getDefaultInstance()) {
            package_ = com.wolfpeng.server.protocol.ResponseOuterClass.Response.newBuilder((com.wolfpeng.server.protocol.ResponseOuterClass.Response) package_)
                .mergeFrom(value).buildPartial();
          } else {
            package_ = value;
          }
          onChanged();
        } else {
          if (packageCase_ == 2) {
            responseBuilder_.mergeFrom(value);
          }
          responseBuilder_.setMessage(value);
        }
        packageCase_ = 2;
        return this;
      }
      /**
       * <code>.server.protocol.Response response = 2;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          if (packageCase_ == 2) {
            packageCase_ = 0;
            package_ = null;
            onChanged();
          }
        } else {
          if (packageCase_ == 2) {
            packageCase_ = 0;
            package_ = null;
          }
          responseBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.server.protocol.Response response = 2;</code>
       */
      public com.wolfpeng.server.protocol.ResponseOuterClass.Response.Builder getResponseBuilder() {
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>.server.protocol.Response response = 2;</code>
       */
      public com.wolfpeng.server.protocol.ResponseOuterClass.ResponseOrBuilder getResponseOrBuilder() {
        if ((packageCase_ == 2) && (responseBuilder_ != null)) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          if (packageCase_ == 2) {
            return (com.wolfpeng.server.protocol.ResponseOuterClass.Response) package_;
          }
          return com.wolfpeng.server.protocol.ResponseOuterClass.Response.getDefaultInstance();
        }
      }
      /**
       * <code>.server.protocol.Response response = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.wolfpeng.server.protocol.ResponseOuterClass.Response, com.wolfpeng.server.protocol.ResponseOuterClass.Response.Builder, com.wolfpeng.server.protocol.ResponseOuterClass.ResponseOrBuilder> 
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          if (!(packageCase_ == 2)) {
            package_ = com.wolfpeng.server.protocol.ResponseOuterClass.Response.getDefaultInstance();
          }
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.wolfpeng.server.protocol.ResponseOuterClass.Response, com.wolfpeng.server.protocol.ResponseOuterClass.Response.Builder, com.wolfpeng.server.protocol.ResponseOuterClass.ResponseOrBuilder>(
                  (com.wolfpeng.server.protocol.ResponseOuterClass.Response) package_,
                  getParentForChildren(),
                  isClean());
          package_ = null;
        }
        packageCase_ = 2;
        onChanged();;
        return responseBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.wolfpeng.server.protocol.NotifyOuterClass.Notify, com.wolfpeng.server.protocol.NotifyOuterClass.Notify.Builder, com.wolfpeng.server.protocol.NotifyOuterClass.NotifyOrBuilder> notifyBuilder_;
      /**
       * <code>.server.protocol.Notify notify = 3;</code>
       */
      public com.wolfpeng.server.protocol.NotifyOuterClass.Notify getNotify() {
        if (notifyBuilder_ == null) {
          if (packageCase_ == 3) {
            return (com.wolfpeng.server.protocol.NotifyOuterClass.Notify) package_;
          }
          return com.wolfpeng.server.protocol.NotifyOuterClass.Notify.getDefaultInstance();
        } else {
          if (packageCase_ == 3) {
            return notifyBuilder_.getMessage();
          }
          return com.wolfpeng.server.protocol.NotifyOuterClass.Notify.getDefaultInstance();
        }
      }
      /**
       * <code>.server.protocol.Notify notify = 3;</code>
       */
      public Builder setNotify(com.wolfpeng.server.protocol.NotifyOuterClass.Notify value) {
        if (notifyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          package_ = value;
          onChanged();
        } else {
          notifyBuilder_.setMessage(value);
        }
        packageCase_ = 3;
        return this;
      }
      /**
       * <code>.server.protocol.Notify notify = 3;</code>
       */
      public Builder setNotify(
          com.wolfpeng.server.protocol.NotifyOuterClass.Notify.Builder builderForValue) {
        if (notifyBuilder_ == null) {
          package_ = builderForValue.build();
          onChanged();
        } else {
          notifyBuilder_.setMessage(builderForValue.build());
        }
        packageCase_ = 3;
        return this;
      }
      /**
       * <code>.server.protocol.Notify notify = 3;</code>
       */
      public Builder mergeNotify(com.wolfpeng.server.protocol.NotifyOuterClass.Notify value) {
        if (notifyBuilder_ == null) {
          if (packageCase_ == 3 &&
              package_ != com.wolfpeng.server.protocol.NotifyOuterClass.Notify.getDefaultInstance()) {
            package_ = com.wolfpeng.server.protocol.NotifyOuterClass.Notify.newBuilder((com.wolfpeng.server.protocol.NotifyOuterClass.Notify) package_)
                .mergeFrom(value).buildPartial();
          } else {
            package_ = value;
          }
          onChanged();
        } else {
          if (packageCase_ == 3) {
            notifyBuilder_.mergeFrom(value);
          }
          notifyBuilder_.setMessage(value);
        }
        packageCase_ = 3;
        return this;
      }
      /**
       * <code>.server.protocol.Notify notify = 3;</code>
       */
      public Builder clearNotify() {
        if (notifyBuilder_ == null) {
          if (packageCase_ == 3) {
            packageCase_ = 0;
            package_ = null;
            onChanged();
          }
        } else {
          if (packageCase_ == 3) {
            packageCase_ = 0;
            package_ = null;
          }
          notifyBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.server.protocol.Notify notify = 3;</code>
       */
      public com.wolfpeng.server.protocol.NotifyOuterClass.Notify.Builder getNotifyBuilder() {
        return getNotifyFieldBuilder().getBuilder();
      }
      /**
       * <code>.server.protocol.Notify notify = 3;</code>
       */
      public com.wolfpeng.server.protocol.NotifyOuterClass.NotifyOrBuilder getNotifyOrBuilder() {
        if ((packageCase_ == 3) && (notifyBuilder_ != null)) {
          return notifyBuilder_.getMessageOrBuilder();
        } else {
          if (packageCase_ == 3) {
            return (com.wolfpeng.server.protocol.NotifyOuterClass.Notify) package_;
          }
          return com.wolfpeng.server.protocol.NotifyOuterClass.Notify.getDefaultInstance();
        }
      }
      /**
       * <code>.server.protocol.Notify notify = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.wolfpeng.server.protocol.NotifyOuterClass.Notify, com.wolfpeng.server.protocol.NotifyOuterClass.Notify.Builder, com.wolfpeng.server.protocol.NotifyOuterClass.NotifyOrBuilder> 
          getNotifyFieldBuilder() {
        if (notifyBuilder_ == null) {
          if (!(packageCase_ == 3)) {
            package_ = com.wolfpeng.server.protocol.NotifyOuterClass.Notify.getDefaultInstance();
          }
          notifyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.wolfpeng.server.protocol.NotifyOuterClass.Notify, com.wolfpeng.server.protocol.NotifyOuterClass.Notify.Builder, com.wolfpeng.server.protocol.NotifyOuterClass.NotifyOrBuilder>(
                  (com.wolfpeng.server.protocol.NotifyOuterClass.Notify) package_,
                  getParentForChildren(),
                  isClean());
          package_ = null;
        }
        packageCase_ = 3;
        onChanged();;
        return notifyBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:server.protocol.Message)
    }

    // @@protoc_insertion_point(class_scope:server.protocol.Message)
    private static final com.wolfpeng.server.protocol.MessageOuterClass.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wolfpeng.server.protocol.MessageOuterClass.Message();
    }

    public static com.wolfpeng.server.protocol.MessageOuterClass.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    public com.wolfpeng.server.protocol.MessageOuterClass.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_protocol_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_protocol_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\022\017server.protocol\032\014Notify" +
      ".proto\032\rRequest.proto\032\016Response.proto\"\233\001" +
      "\n\007Message\022+\n\007request\030\001 \001(\0132\030.server.prot" +
      "ocol.RequestH\000\022-\n\010response\030\002 \001(\0132\031.serve" +
      "r.protocol.ResponseH\000\022)\n\006notify\030\003 \001(\0132\027." +
      "server.protocol.NotifyH\000B\t\n\007PackageB\036\n\034c" +
      "om.wolfpeng.server.protocolb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.wolfpeng.server.protocol.NotifyOuterClass.getDescriptor(),
          com.wolfpeng.server.protocol.RequestOuterClass.getDescriptor(),
          com.wolfpeng.server.protocol.ResponseOuterClass.getDescriptor(),
        }, assigner);
    internal_static_server_protocol_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_server_protocol_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_protocol_Message_descriptor,
        new java.lang.String[] { "Request", "Response", "Notify", "Package", });
    com.wolfpeng.server.protocol.NotifyOuterClass.getDescriptor();
    com.wolfpeng.server.protocol.RequestOuterClass.getDescriptor();
    com.wolfpeng.server.protocol.ResponseOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
